### ISSUE TITLE
Installation via DigitalOcean 1 Click Install Cannot Connect to Database

### ISSUE THREAD

**Issue by mattwaler** [directus/do-one-click#4]
# Bug Report

When following the instructions following a digitalocean 1 click install, connecting to the database is unsuccessful.

## Steps to Reproduce

1. Create new server/directus install via digitalocean
2. Navigate to /admin
3. Create Admin Account Credentials
4. Insert Database Credentials (In screenshot, PW grabbed from `/root/.digitalocean_password` tried using both the root_mysql_pass and directus_mysql_pass values)
5. Error occurs

## Expected Behavior

Installation completes and redirects to login.

## Actual Behavior

Setup process cannot complete.

## Other Context & Screenshots

<img width="1512" alt="screen shot 2019-03-04 at 1 23 10 pm" src="https://user-images.githubusercontent.com/32300026/53754096-eded5200-3e80-11e9-8c3d-0631e5731591.png">

## Technical Details

- Device: Macbook Pro
- OS: Mac OS Mojave, Google Chrome
- Web Server: Apache
- PHP Version: 7.2
- Database: MySQL
- Install Method: DigitalOcean 1-click

**Comment by pauldailly** [comment]
Hi @WoLfulus I just wanted to follow up on this as it seems the issue is with me. I hadn't realised that when creating a new droplet from snapshot, the credentials for accessing database would change e.g those held in `~/credentials.txt`. Therefore my config file (in `/var/directus/config`) was still using the db credentials of the original droplet, hence why the directus app could not access the database.

I presume there is some sort of start up script run when the droplet is instantiated which sets up these credentials?

Apologies for taking up your time with this and thanks for your willingness to help!

**Comment by Adeolamorren** [comment]
I'm getting the same problem as mentioned above, using digital ocean, using directus as username and the password. Invalid database connection is what  keep getting....

**Comment by WoLfulus** [comment]
@pauldailly sorry, I totally missed your reply. I'll check this before the next release.
